In [259]:
import pandas as pd  # 데이터 분석을 위한 라이브러리
import numpy as np   # 넘파이 : 숫자 계산
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
# 워닝(버전, 업데이트 문제, 에러는 아님) 코드는 실행되는데 정보. 귀찮을 때 워닝 끄기
import warnings
warnings.filterwarnings('ignore')

In [2]:
ls

Untitled.ipynb                 크롤링_술.ipynb
gwasilju.xlsx                  크롤링_술_술담화.ipynb
jeunglyuju.xlsx                크롤링술_v2.ipynb
takju.xlsx                     술담화크롤링찬.xlsx
yag_cheongju.xlsx              술담화크롤링찬2.xlsx


In [519]:
takju= pd.read_excel('takju.xlsx')
gwasilju= pd.read_excel('gwasilju.xlsx')
jeunglyuju= pd.read_excel('jeunglyuju.xlsx')
yag_cheongju= pd.read_excel('yag_cheongju.xlsx')

In [520]:
takju['section']='takju'
gwasilju['section']='gwasilju'
jeunglyuju['section']='jeunglyuju'
yag_cheongju['section']='yag_cheongju'

In [521]:
df= pd.concat([takju,gwasilju,jeunglyuju,yag_cheongju],ignore_index=True,sort=False)
df

Unnamed: 0                name    price alcohol_degree      capacity  \
0             1     마크홀리 6% [3병/6병]  23,700원             6%         650ml   
1             2     참주가 라봉 막걸리 X 4병  24,000원           5.5%         650ml   
2             3  참주가 솔 막걸리 [6병/12병]  15,000원           5.5%         650ml   
3             4          부자 막걸리 10%   4,900원            10%         375ml   
4             5            바텐더의 막걸리   9,000원            14%         500ml   
..          ...                 ...      ...            ...           ...   
278          55          매실 향기 담은 술  25,920원            14%         500ml   
279          56              삼양춘 청주  17,500원            15%         500ml   
280          57              맑은 문희주  46,000원            13%  500ml, 750ml   
281          58            오메기술 15%  16,000원            15%         375ml   
282          59               감사 블루  15,000원            14%         375ml   

                           food_name sweet sour plain  body carbonic_acid  \
0            ['닭발', '주꾸미 볶음', '떡볶이']    강함   약함    중간    중간            없음   
1            ['짜장면', '크림 파스타', '피자']    약함   강함    강함    약함            강함   
2       ['삼계탕', '버섯구이', '차돌박이 숙주 찜']    약함   약함    중간    약함            중간   
3        ['녹두전', '순대 볶음', '나가사키 짬뽕']    약함   강함    강함    강함            없음   
4           ['비포선셋', '밀키웨이', '화채펀치']    중간   중간    강함    중간            없음   
..                               ...   ...  ...   ...   ...           ...   
278            ['방어회', '감자전', '탕수육']    중간   강함    중간    중간            중간   
279          ['과일치즈', '조개찜', '연어초밥']    중간   중간    중간    중간            강함   
280  ['소고기 안심', '차돌박이 숙주 볶음', '생선회']  매우강함   약함  매우약함  매우강함            약함   
281          ['수육', '순대 볶음', '돼지국밥']    중간   약함  매우약함    중간            강함   
282        ['고등어구이', '육전', '대패 삼겹살']  매우약함   중간    강함    중간            중간   

                                                flavor       section  
0    ('sweet_강함', 'sour_약함', 'plain_중간', 'body_중간',...         takju  
1    ('sweet_약함', 'sour_강함', 'plain_강함', 'body_약함',...         takju  
2    ('sweet_약함', 'sour_약함', 'plain_중간', 'body_약함',...         takju  
3    ('sweet_약함', 'sour_강함', 'plain_강함', 'body_강함',...         takju  
4    ('sweet_중간', 'sour_중간', 'plain_강함', 'body_중간',...         takju  
..                                                 ...           ...  
278  ('sweet_중간', 'sour_강함', 'plain_중간', 'body_중간',...  yag_cheongju  
279  ('sweet_중간', 'sour_중간', 'plain_중간', 'body_중간',...  yag_cheongju  
280  ('sweet_매우강함', 'sour_약함', 'plain_매우약함', 'body_...  yag_cheongju  
281  ('sweet_중간', 'sour_약함', 'plain_매우약함', 'body_중간...  yag_cheongju  
282  ('sweet_매우약함', 'sour_중간', 'plain_강함', 'body_중간...  yag_cheongju  

[283 rows x 13 columns]

In [522]:
# 중복값 제거
df=df.drop_duplicates(['name'],keep='first',ignore_index=True)
df

Unnamed: 0                name    price alcohol_degree      capacity  \
0             1     마크홀리 6% [3병/6병]  23,700원             6%         650ml   
1             2     참주가 라봉 막걸리 X 4병  24,000원           5.5%         650ml   
2             3  참주가 솔 막걸리 [6병/12병]  15,000원           5.5%         650ml   
3             4          부자 막걸리 10%   4,900원            10%         375ml   
4             5            바텐더의 막걸리   9,000원            14%         500ml   
..          ...                 ...      ...            ...           ...   
275          55          매실 향기 담은 술  25,920원            14%         500ml   
276          56              삼양춘 청주  17,500원            15%         500ml   
277          57              맑은 문희주  46,000원            13%  500ml, 750ml   
278          58            오메기술 15%  16,000원            15%         375ml   
279          59               감사 블루  15,000원            14%         375ml   

                           food_name sweet sour plain  body carbonic_acid  \
0            ['닭발', '주꾸미 볶음', '떡볶이']    강함   약함    중간    중간            없음   
1            ['짜장면', '크림 파스타', '피자']    약함   강함    강함    약함            강함   
2       ['삼계탕', '버섯구이', '차돌박이 숙주 찜']    약함   약함    중간    약함            중간   
3        ['녹두전', '순대 볶음', '나가사키 짬뽕']    약함   강함    강함    강함            없음   
4           ['비포선셋', '밀키웨이', '화채펀치']    중간   중간    강함    중간            없음   
..                               ...   ...  ...   ...   ...           ...   
275            ['방어회', '감자전', '탕수육']    중간   강함    중간    중간            중간   
276          ['과일치즈', '조개찜', '연어초밥']    중간   중간    중간    중간            강함   
277  ['소고기 안심', '차돌박이 숙주 볶음', '생선회']  매우강함   약함  매우약함  매우강함            약함   
278          ['수육', '순대 볶음', '돼지국밥']    중간   약함  매우약함    중간            강함   
279        ['고등어구이', '육전', '대패 삼겹살']  매우약함   중간    강함    중간            중간   

                                                flavor       section  
0    ('sweet_강함', 'sour_약함', 'plain_중간', 'body_중간',...         takju  
1    ('sweet_약함', 'sour_강함', 'plain_강함', 'body_약함',...         takju  
2    ('sweet_약함', 'sour_약함', 'plain_중간', 'body_약함',...         takju  
3    ('sweet_약함', 'sour_강함', 'plain_강함', 'body_강함',...         takju  
4    ('sweet_중간', 'sour_중간', 'plain_강함', 'body_중간',...         takju  
..                                                 ...           ...  
275  ('sweet_중간', 'sour_강함', 'plain_중간', 'body_중간',...  yag_cheongju  
276  ('sweet_중간', 'sour_중간', 'plain_중간', 'body_중간',...  yag_cheongju  
277  ('sweet_매우강함', 'sour_약함', 'plain_매우약함', 'body_...  yag_cheongju  
278  ('sweet_중간', 'sour_약함', 'plain_매우약함', 'body_중간...  yag_cheongju  
279  ('sweet_매우약함', 'sour_중간', 'plain_강함', 'body_중간...  yag_cheongju  

[280 rows x 13 columns]

데이터 전처리

In [524]:
# 불필요한 문자제거
df['food_name']=df['food_name'].str.replace("'","")
df

Unnamed: 0                name    price alcohol_degree      capacity  \
0             1     마크홀리 6% [3병/6병]  23,700원             6%         650ml   
1             2     참주가 라봉 막걸리 X 4병  24,000원           5.5%         650ml   
2             3  참주가 솔 막걸리 [6병/12병]  15,000원           5.5%         650ml   
3             4          부자 막걸리 10%   4,900원            10%         375ml   
4             5            바텐더의 막걸리   9,000원            14%         500ml   
..          ...                 ...      ...            ...           ...   
275          55          매실 향기 담은 술  25,920원            14%         500ml   
276          56              삼양춘 청주  17,500원            15%         500ml   
277          57              맑은 문희주  46,000원            13%  500ml, 750ml   
278          58            오메기술 15%  16,000원            15%         375ml   
279          59               감사 블루  15,000원            14%         375ml   

                     food_name sweet sour plain  body carbonic_acid  \
0            [닭발, 주꾸미 볶음, 떡볶이]    강함   약함    중간    중간            없음   
1            [짜장면, 크림 파스타, 피자]    약함   강함    강함    약함            강함   
2       [삼계탕, 버섯구이, 차돌박이 숙주 찜]    약함   약함    중간    약함            중간   
3        [녹두전, 순대 볶음, 나가사키 짬뽕]    약함   강함    강함    강함            없음   
4           [비포선셋, 밀키웨이, 화채펀치]    중간   중간    강함    중간            없음   
..                         ...   ...  ...   ...   ...           ...   
275            [방어회, 감자전, 탕수육]    중간   강함    중간    중간            중간   
276          [과일치즈, 조개찜, 연어초밥]    중간   중간    중간    중간            강함   
277  [소고기 안심, 차돌박이 숙주 볶음, 생선회]  매우강함   약함  매우약함  매우강함            약함   
278          [수육, 순대 볶음, 돼지국밥]    중간   약함  매우약함    중간            강함   
279        [고등어구이, 육전, 대패 삼겹살]  매우약함   중간    강함    중간            중간   

                                                flavor       section  
0    ('sweet_강함', 'sour_약함', 'plain_중간', 'body_중간',...         takju  
1    ('sweet_약함', 'sour_강함', 'plain_강함', 'body_약함',...         takju  
2    ('sweet_약함', 'sour_약함', 'plain_중간', 'body_약함',...         takju  
3    ('sweet_약함', 'sour_강함', 'plain_강함', 'body_강함',...         takju  
4    ('sweet_중간', 'sour_중간', 'plain_강함', 'body_중간',...         takju  
..                                                 ...           ...  
275  ('sweet_중간', 'sour_강함', 'plain_중간', 'body_중간',...  yag_cheongju  
276  ('sweet_중간', 'sour_중간', 'plain_중간', 'body_중간',...  yag_cheongju  
277  ('sweet_매우강함', 'sour_약함', 'plain_매우약함', 'body_...  yag_cheongju  
278  ('sweet_중간', 'sour_약함', 'plain_매우약함', 'body_중간...  yag_cheongju  
279  ('sweet_매우약함', 'sour_중간', 'plain_강함', 'body_중간...  yag_cheongju  

[280 rows x 13 columns]

In [525]:
# 리스트화 
for i in range(len(df)):
    df['food_name'][i]=df['food_name'][i].replace("[","").replace("]","").replace(" ","").split(",")

In [526]:
# 특정 단어 찾기 
a_list=[]
food_name_input=input()
for i in range(len(df)):
    for j in df['food_name'][i]:
        if j==food_name_input:
            a_list.append(i)
check_list = df.loc[a_list]

육전


In [527]:
check_list

Unnamed: 0              name    price alcohol_degree capacity  \
28           29            벗이랑 홍국  13,500원            15%    500ml   
38           39  가덕 순쌀 생 막걸리 X 6병  18,000원             6%    750ml   
66           67   오미자 생 막걸리 X 10병  23,000원           6.5%    500ml   
105          38            오미로제 연  50,000원             8%    750ml   
141           8           이강주 25%  13,000원            25%    375ml   
152          19            여유 40%  25,800원            40%    375ml   
279          59             감사 블루  15,000원            14%    375ml   

                food_name sweet sour plain body carbonic_acid  \
28   [육전, 고추장삼겹살, 양념장어구이]    중간   약함    강함   강함            없음   
38        [육전, 해물파전, 감자전]    약함   약함    강함   중간            중간   
66         [수육, 계란말이, 육전]    중간   중간    중간   약함            중간   
105  [새우오일파스타, 연어샐러드, 육전]    약함   강함    약함   중간            강함   
141     [떡갈비, 육전, 데리야끼치킨]    약함   강함    강함   중간            중간   
152      [육전, 방어회, 양갈비구이]    약함   강함    강함   강함            강함   
279    [고등어구이, 육전, 대패삼겹살]  매우약함   중간    강함   중간            중간   

                                                flavor       section  
28   ('sweet_중간', 'sour_약함', 'plain_강함', 'body_강함',...         takju  
38   ('sweet_약함', 'sour_약함', 'plain_강함', 'body_중간',...         takju  
66   ('sweet_중간', 'sour_중간', 'plain_중간', 'body_약함',...         takju  
105  ('sweet_약함', 'sour_강함', 'plain_약함', 'body_중간',...      gwasilju  
141  ('sweet_약함', 'sour_강함', 'plain_강함', 'body_중간',...    jeunglyuju  
152  ('sweet_약함', 'sour_강함', 'plain_강함', 'body_강함',...    jeunglyuju  
279  ('sweet_매우약함', 'sour_중간', 'plain_강함', 'body_중간...  yag_cheongju

In [528]:
#섹션별 한종류만
check_list=check_list.drop_duplicates(subset='section')
check_list.name
for a in check_list.name:
    print(a)

벗이랑 홍국
오미로제 연
이강주 25%
감사 블루


In [529]:
# 어울리는 안주를 CountVectorizer를 위해 컬럼 추가
df['food_name_literal'] = df['food_name'].apply(lambda x : (' ').join(x))
count_vect = CountVectorizer(min_df=0, ngram_range=(1,3))
food_mat = count_vect.fit_transform(df['food_name_literal'])
food_sim = cosine_similarity(food_mat, food_mat)
food_sim_sorted_ind =food_sim.argsort()[:,::-1]
print(food_sim_sorted_ind[:5])

[[  0 154 200 ... 177 176 139]
 [  1 133 122 ... 178 177   0]
 [  2 170 198 ... 175 174   0]
 [  3 278 230 ... 177 176   0]
 [  4 279  95 ... 178 177   0]]


In [530]:
df

Unnamed: 0                name    price alcohol_degree      capacity  \
0             1     마크홀리 6% [3병/6병]  23,700원             6%         650ml   
1             2     참주가 라봉 막걸리 X 4병  24,000원           5.5%         650ml   
2             3  참주가 솔 막걸리 [6병/12병]  15,000원           5.5%         650ml   
3             4          부자 막걸리 10%   4,900원            10%         375ml   
4             5            바텐더의 막걸리   9,000원            14%         500ml   
..          ...                 ...      ...            ...           ...   
275          55          매실 향기 담은 술  25,920원            14%         500ml   
276          56              삼양춘 청주  17,500원            15%         500ml   
277          57              맑은 문희주  46,000원            13%  500ml, 750ml   
278          58            오메기술 15%  16,000원            15%         375ml   
279          59               감사 블루  15,000원            14%         375ml   

                  food_name sweet sour plain  body carbonic_acid  \
0          [닭발, 주꾸미볶음, 떡볶이]    강함   약함    중간    중간            없음   
1          [짜장면, 크림파스타, 피자]    약함   강함    강함    약함            강함   
2      [삼계탕, 버섯구이, 차돌박이숙주찜]    약함   약함    중간    약함            중간   
3       [녹두전, 순대볶음, 나가사키짬뽕]    약함   강함    강함    강함            없음   
4        [비포선셋, 밀키웨이, 화채펀치]    중간   중간    강함    중간            없음   
..                      ...   ...  ...   ...   ...           ...   
275         [방어회, 감자전, 탕수육]    중간   강함    중간    중간            중간   
276       [과일치즈, 조개찜, 연어초밥]    중간   중간    중간    중간            강함   
277  [소고기안심, 차돌박이숙주볶음, 생선회]  매우강함   약함  매우약함  매우강함            약함   
278        [수육, 순대볶음, 돼지국밥]    중간   약함  매우약함    중간            강함   
279      [고등어구이, 육전, 대패삼겹살]  매우약함   중간    강함    중간            중간   

                                                flavor       section  \
0    ('sweet_강함', 'sour_약함', 'plain_중간', 'body_중간',...         takju   
1    ('sweet_약함', 'sour_강함', 'plain_강함', 'body_약함',...         takju   
2    ('sweet_약함', 'sour_약함', 'plain_중간', 'body_약함',...         takju   
3    ('sweet_약함', 'sour_강함', 'plain_강함', 'body_강함',...         takju   
4    ('sweet_중간', 'sour_중간', 'plain_강함', 'body_중간',...         takju   
..                                                 ...           ...   
275  ('sweet_중간', 'sour_강함', 'plain_중간', 'body_중간',...  yag_cheongju   
276  ('sweet_중간', 'sour_중간', 'plain_중간', 'body_중간',...  yag_cheongju   
277  ('sweet_매우강함', 'sour_약함', 'plain_매우약함', 'body_...  yag_cheongju   
278  ('sweet_중간', 'sour_약함', 'plain_매우약함', 'body_중간...  yag_cheongju   
279  ('sweet_매우약함', 'sour_중간', 'plain_강함', 'body_중간...  yag_cheongju   

      food_name_literal  
0          닭발 주꾸미볶음 떡볶이  
1          짜장면 크림파스타 피자  
2      삼계탕 버섯구이 차돌박이숙주찜  
3       녹두전 순대볶음 나가사키짬뽕  
4        비포선셋 밀키웨이 화채펀치  
..                  ...  
275         방어회 감자전 탕수육  
276       과일치즈 조개찜 연어초밥  
277  소고기안심 차돌박이숙주볶음 생선회  
278        수육 순대볶음 돼지국밥  
279      고등어구이 육전 대패삼겹살  

[280 rows x 14 columns]

In [531]:
# 코사인 유사도를 기준으로 역순으로 정렬해주는 함수 구현
def find_sim_food_ver1(df,sorted_ind,title_food, top_n=10):
    title = df[df['name']== title_food]
    
    title_index = title.index.values
    similar_indexes = sorted_ind[title_index,:(top_n)]
    
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)
    
    return df.iloc[similar_indexes]

In [551]:
# 4가지 종류 추천 알고리즘 실행
dict = {}
count_num = 0
for i in check_list.name:
    dict[count_num]=find_sim_food_ver1(df,food_sim_sorted_ind,i,9)
    count_num += 1
    

[[ 28 279 152  66  38 158 105 141 102]]
[[105 279 152 203  66  38 110  28 172]]
[[141 279 145 161 219  49 152  28  89]]
[[279 152  66 234  38  28 163 105 273]]


In [552]:
#데이터프레임 합치기
df_list = []
for r_list in range(len(dict)):
    globals()[f'df_{r_list}'] = dict[r_list]
    df_list.append(globals()[f'df_{r_list}'])

In [553]:
#데이터프레임 합치기2
df_df = pd.concat(df_list,ignore_index=True,sort=False)


In [554]:
#합친 데이터 중복 제거
df_df=df_df.drop_duplicates(['name'],keep='first',ignore_index=True)

In [555]:
df_df

Unnamed: 0              name    price alcohol_degree      capacity  \
0           29            벗이랑 홍국  13,500원            15%         500ml   
1           59             감사 블루  15,000원            14%         375ml   
2           19            여유 40%  25,800원            40%         375ml   
3           67   오미자 생 막걸리 X 10병  23,000원           6.5%         500ml   
4           39  가덕 순쌀 생 막걸리 X 6병  18,000원             6%         750ml   
5           25            무작 30%  35,000원            30%         200ml   
6           38            오미로제 연  50,000원             8%         750ml   
7            8           이강주 25%  13,000원            25%         375ml   
8           35         추사 블루 스위트  20,000원            11%         375ml   
9           72  아이엠더문 오리지널 / 화이트  28,000원            17%  375ml, 750ml   
10          43            오미로제 결  99,000원            12%         750ml   
11          39              술샘16  12,000원            16%         375ml   
12          12           상록수 40%  26,000원            40%         500ml   
13          28            솔섬 25%  10,000원            25%         375ml   
14          89          진맥소주 22%  22,000원            22%         375ml   
15          50      술취한 원숭이 X 4병  36,000원          10.8%         375ml   
16          22       여포의 꿈 화이트와인  25,000원            12%  375ml, 750ml   
17          14              모든날에  28,000원            15%         500ml   
18          30    안동소주 일품 40% 골드  27,000원            40%         500ml   
19          53                하타  20,000원            16%         500ml   

                food_name sweet sour plain body carbonic_acid  \
0    [육전, 고추장삼겹살, 양념장어구이]    중간   약함    강함   강함            없음   
1      [고등어구이, 육전, 대패삼겹살]  매우약함   중간    강함   중간            중간   
2        [육전, 방어회, 양갈비구이]    약함   강함    강함   강함            강함   
3          [수육, 계란말이, 육전]    중간   중간    중간   약함            중간   
4         [육전, 해물파전, 감자전]    약함   약함    강함   중간            중간   
5   [메밀전병, 고추장삼겹살, 해물순두부]    중간   중간    강함   강함            강함   
6    [새우오일파스타, 연어샐러드, 육전]    약함   강함    약함   중간            강함   
7       [떡갈비, 육전, 데리야끼치킨]    약함   강함    강함   중간            중간   
8   [피칸파이, 까르보나라, 블루베리파이]    중간   약함    약함   약함            없음   
9     [카나페, 연어샐러드, 치즈케이크]  매우약함   강함    강함   강함            약함   
10     [연어샐러드, 생선회, 더덕구이]    중간   중간    약함   중간            중간   
11     [막국수, 과일치즈, 연어샐러드]    없음   강함    강함   약함            중간   
12       [떡갈비, 빈대떡, 꿔바로우]    중간   강함    강함   중간            약함   
13       [떡갈비, 양고기, 고등어회]  매우약함   중간    강함   중간            중간   
14         [떡갈비, 수육, 전어회]    약함   중간    중간   중간            약함   
15       [떡갈비, 불고기, 양념치킨]    중간   약함    강함   강함            없음   
16    [떡갈비, 연어스테이크, 치킨너겟]    중간   강함    중간   중간            없음   
17      [간장게장, 고등어구이, 찜닭]    약함   강함    강함   약함            강함   
18     [고등어구이, 산적꼬치, 삼겹살]    강함   약함    강함   강함            강함   
19      [오뎅탕, 고등어구이, 생선회]    약함   약함    강함   약함            약함   

                                               flavor       section  \
0   ('sweet_중간', 'sour_약함', 'plain_강함', 'body_강함',...         takju   
1   ('sweet_매우약함', 'sour_중간', 'plain_강함', 'body_중간...  yag_cheongju   
2   ('sweet_약함', 'sour_강함', 'plain_강함', 'body_강함',...    jeunglyuju   
3   ('sweet_중간', 'sour_중간', 'plain_중간', 'body_약함',...         takju   
4   ('sweet_약함', 'sour_약함', 'plain_강함', 'body_중간',...         takju   
5   ('sweet_중간', 'sour_중간', 'plain_강함', 'body_강함',...    jeunglyuju   
6   ('sweet_약함', 'sour_강함', 'plain_약함', 'body_중간',...      gwasilju   
7   ('sweet_약함', 'sour_강함', 'plain_강함', 'body_중간',...    jeunglyuju   
8   ('sweet_중간', 'sour_약함', 'plain_약함', 'body_약함',...      gwasilju   
9   ('sweet_매우약함', 'sour_강함', 'plain_강함', 'body_강함...    jeunglyuju   
10  ('sweet_중간', 'sour_중간', 'plain_약함', 'body_중간',...      gwasilju   
11  ('sweet_없음', 'sour_강함', 'plain_강함', 'body_약함',...    jeunglyuju   
12  ('sweet_중간', 'sour_강함', 'plain_강함', 'body_중간',...    jeunglyuju   
13  ('sweet_매우약함', 'sour_중간', 'plain_강함', 'body_중간...    jeunglyuju   
14  ('sweet_약함', '

In [556]:
# takju만 선택하여 보기
print('takju')
df_df[df_df['section']=='takju'].head(4)

takju


Unnamed: 0              name    price alcohol_degree capacity  \
0           29            벗이랑 홍국  13,500원            15%    500ml   
3           67   오미자 생 막걸리 X 10병  23,000원           6.5%    500ml   
4           39  가덕 순쌀 생 막걸리 X 6병  18,000원             6%    750ml   
15          50      술취한 원숭이 X 4병  36,000원          10.8%    375ml   

               food_name sweet sour plain body carbonic_acid  \
0   [육전, 고추장삼겹살, 양념장어구이]    중간   약함    강함   강함            없음   
3         [수육, 계란말이, 육전]    중간   중간    중간   약함            중간   
4        [육전, 해물파전, 감자전]    약함   약함    강함   중간            중간   
15      [떡갈비, 불고기, 양념치킨]    중간   약함    강함   강함            없음   

                                               flavor section  \
0   ('sweet_중간', 'sour_약함', 'plain_강함', 'body_강함',...   takju   
3   ('sweet_중간', 'sour_중간', 'plain_중간', 'body_약함',...   takju   
4   ('sweet_약함', 'sour_약함', 'plain_강함', 'body_중간',...   takju   
15  ('sweet_중간', 'sour_약함', 'plain_강함', 'body_강함',...   takju   

   food_name_literal  
0   육전 고추장삼겹살 양념장어구이  
3         수육 계란말이 육전  
4        육전 해물파전 감자전  
15      떡갈비 불고기 양념치킨

In [557]:
print('gwasilju')
df_df[df_df['section']=='gwasilju'].head(4)

gwasilju


Unnamed: 0         name    price alcohol_degree      capacity  \
6           38       오미로제 연  50,000원             8%         750ml   
8           35    추사 블루 스위트  20,000원            11%         375ml   
10          43       오미로제 결  99,000원            12%         750ml   
16          22  여포의 꿈 화이트와인  25,000원            12%  375ml, 750ml   

                food_name sweet sour plain body carbonic_acid  \
6    [새우오일파스타, 연어샐러드, 육전]    약함   강함    약함   중간            강함   
8   [피칸파이, 까르보나라, 블루베리파이]    중간   약함    약함   약함            없음   
10     [연어샐러드, 생선회, 더덕구이]    중간   중간    약함   중간            중간   
16    [떡갈비, 연어스테이크, 치킨너겟]    중간   강함    중간   중간            없음   

                                               flavor   section  \
6   ('sweet_약함', 'sour_강함', 'plain_약함', 'body_중간',...  gwasilju   
8   ('sweet_중간', 'sour_약함', 'plain_약함', 'body_약함',...  gwasilju   
10  ('sweet_중간', 'sour_중간', 'plain_약함', 'body_중간',...  gwasilju   
16  ('sweet_중간', 'sour_강함', 'plain_중간', 'body_중간',...  gwasilju   

    food_name_literal  
6    새우오일파스타 연어샐러드 육전  
8   피칸파이 까르보나라 블루베리파이  
10     연어샐러드 생선회 더덕구이  
16    떡갈비 연어스테이크 치킨너겟

In [558]:
print('jeunglyuju')
df_df[df_df['section']=='jeunglyuju'].head(4)

jeunglyuju


Unnamed: 0              name    price alcohol_degree      capacity  \
2          19            여유 40%  25,800원            40%         375ml   
5          25            무작 30%  35,000원            30%         200ml   
7           8           이강주 25%  13,000원            25%         375ml   
9          72  아이엠더문 오리지널 / 화이트  28,000원            17%  375ml, 750ml   

               food_name sweet sour plain body carbonic_acid  \
2       [육전, 방어회, 양갈비구이]    약함   강함    강함   강함            강함   
5  [메밀전병, 고추장삼겹살, 해물순두부]    중간   중간    강함   강함            강함   
7      [떡갈비, 육전, 데리야끼치킨]    약함   강함    강함   중간            중간   
9    [카나페, 연어샐러드, 치즈케이크]  매우약함   강함    강함   강함            약함   

                                              flavor     section  \
2  ('sweet_약함', 'sour_강함', 'plain_강함', 'body_강함',...  jeunglyuju   
5  ('sweet_중간', 'sour_중간', 'plain_강함', 'body_강함',...  jeunglyuju   
7  ('sweet_약함', 'sour_강함', 'plain_강함', 'body_중간',...  jeunglyuju   
9  ('sweet_매우약함', 'sour_강함', 'plain_강함', 'body_강함...  jeunglyuju   

   food_name_literal  
2       육전 방어회 양갈비구이  
5  메밀전병 고추장삼겹살 해물순두부  
7      떡갈비 육전 데리야끼치킨  
9    카나페 연어샐러드 치즈케이크

In [559]:
print('yag_cheongju')
df_df[df_df['section']=='yag_cheongju'].head(4)

yag_cheongju


Unnamed: 0   name    price alcohol_degree capacity           food_name  \
1           59  감사 블루  15,000원            14%    375ml  [고등어구이, 육전, 대패삼겹살]   
17          14   모든날에  28,000원            15%    500ml   [간장게장, 고등어구이, 찜닭]   
19          53     하타  20,000원            16%    500ml   [오뎅탕, 고등어구이, 생선회]   

   sweet sour plain body carbonic_acid  \
1   매우약함   중간    강함   중간            중간   
17    약함   강함    강함   약함            강함   
19    약함   약함    강함   약함            약함   

                                               flavor       section  \
1   ('sweet_매우약함', 'sour_중간', 'plain_강함', 'body_중간...  yag_cheongju   
17  ('sweet_약함', 'sour_강함', 'plain_강함', 'body_약함',...  yag_cheongju   
19  ('sweet_약함', 'sour_약함', 'plain_강함', 'body_약함',...  yag_cheongju   

   food_name_literal  
1     고등어구이 육전 대패삼겹살  
17     간장게장 고등어구이 찜닭  
19     오뎅탕 고등어구이 생선회

In [26]:
#공부
title_in = drink_title.index.values
title_in

array([279])

In [29]:
#공부
similar_indexes = food_sim_sorted_ind[title_in,:10]
similar_indexes

array([[279, 231,   2, 119, 120, 110, 275,  63,  60,  59]])

In [30]:
#공부
similar_indexes = similar_indexes.reshape(-1)
print(similar_indexes)

[279 231   2 119 120 110 275  63  60  59]


In [31]:
#공부
df.iloc[similar_indexes]

Unnamed: 0                   name    price alcohol_degree      capacity  \
279          56                 맑은 문희주  46,000원            13%  500ml, 750ml   
231           8                  매화깊은밤  12,000원             8%         375ml   
2             2     참주가 솔 막걸리 [6병/12병]  15,000원           5.5%         650ml   
119          52          세인트하우스 오미자 와인  20,000원            12%         500ml   
120          53         세인트하우스 아로니아 와인  23,000원            12%         500ml   
110          43                 오미로제 결  99,000원            12%         750ml   
275          52                     하타  20,000원            16%         500ml   
63           64                    백년향  13,000원            10%         500ml   
60           61  [8/8 일괄출고] 문희 오미자 가향주  26,000원            12%  500ml, 700ml   
59           60                     문희  23,000원            13%  500ml, 700ml   

                        food_name sweet sour plain  body carbonic_acid  \
279     [소고기 안심, 차돌박이 숙주 볶음, 생선회]  매우강함   약함  매우약함  매우강함            약함   
231  [차돌박이 숙주 볶음, 시저 샐러드, 백순대 볶음]    강함   중간    약함    중간            중간   
2          [삼계탕, 버섯구이, 차돌박이 숙주 찜]    약함   약함    중간    약함            중간   
119            [소고기 안심, 피자, 닭가슴살]    약함   중간  매우강함    약함            없음   
120        [소고기 안심, 삼겹살, 목살 스테이크]    약함   중간  매우강함    약함            없음   
110            [연어샐러드, 생선회, 더덕구이]    중간   중간    약함    중간            중간   
275             [오뎅탕, 고등어구이, 생선회]    약함   약함    강함    약함            약함   
63            [닭볶음탕, 갈비찜, 주꾸미 볶음]    약함   강함    강함    강함            없음   
60            [아구찜, 스테이크, 주꾸미 볶음]  매우강함   중간    약함  매우강함            없음   
59               [수육, 순대 볶음, 닭갈비]  매우강함   약함    약함  매우강함            없음   

                                                flavor       section  
279  ('sweet_매우강함', 'sour_약함', 'plain_매우약함', 'body_...  yag_cheongju  
231  ('sweet_강함', 'sour_중간', 'plain_약함', 'body_중간',...  yag_cheongju  
2    ('sweet_약함', 'sour_약함', 'plain_중간', 'body_약함',...         takju  
119  ('sweet_약함', 'sour_중간', 'plain_매우강함', 'body_약함...      gwasilju  
120  ('sweet_약함', 'sour_중간', 'plain_매우강함', 'body_약함...      gwasilju  
110  ('sweet_중간', 'sour_중간', 'plain_약함', 'body_중간',...      gwasilju  
275  ('sweet_약함', 'sour_약함', 'plain_강함', 'body_약함',...  yag_cheongju  
63   ('sweet_약함', 'sour_강함', 'plain_강함', 'body_강함',...         takju  
60   ('sweet_매우강함', 'sour_중간', 'plain_약함', 'body_매우...         takju  
59   ('sweet_매우강함', 'sour_약함', 'plain_약함', 'body_매우...         takju

In [41]:
#공부
a = find_sim_food_ver1(df,food_sim_sorted_ind,'감자전',10)
a

[]


Empty DataFrame
Columns: [Unnamed: 0, name, price, alcohol_degree, capacity, food_name, sweet, sour, plain, body, carbonic_acid, flavor, section]
Index: []

In [204]:
#요리개수
food_li=[]

for value in food_list:
    if value not in food_li:
        food_li.append(value)

In [207]:
len(food_li)

306

In [550]:
food_li

['닭발',
 '주꾸미볶음',
 '떡볶이',
 '짜장면',
 '크림파스타',
 '피자',
 '삼계탕',
 '버섯구이',
 '차돌박이숙주찜',
 '녹두전',
 '순대볶음',
 '나가사키짬뽕',
 '비포선셋',
 '밀키웨이',
 '화채펀치',
 '메밀전병',
 '도토리묵무침',
 '두부김치',
 '맥앤치즈',
 '돼지국밥',
 '닭곰탕',
 '간장게장',
 '양념갈비',
 '찜닭',
 '낙지볶음',
 '불닭볶음면',
 '수육',
 '부추전',
 '두부부침',
 '샤브샤브',
 '육회',
 '연포탕',
 '도넛',
 '양갈비구이',
 '훈제삼겹살',
 '탕수육',
 '칠리새우',
 '양념치킨',
 '전복버터구이',
 '장어구이',
 '오돌뼈',
 '막창',
 '돼지껍데기',
 '통닭구이',
 '까르보나라',
 '돈까스',
 '콘치즈',
 '닭볶음탕',
 '고추장찌개',
 '콩나물무침',
 '아구찜',
 '간장불고기',
 '오징어튀김',
 '오리고기',
 '불고기',
 '찹스테이크',
 '불족발',
 '곱창',
 '훈제오리냉채',
 '라자냐',
 '가지볶음',
 '버터갈릭새우',
 '갈비구이',
 '로제떡볶이',
 '해물파전',
 '골뱅이무침',
 '감자전',
 '브루스케타',
 '갈비찜',
 '육전',
 '고추장삼겹살',
 '양념장어구이',
 '초콜릿',
 '동치미막국수',
 '초코케이크',
 '과일치즈',
 '크로플',
 '오뎅탕',
 '돼지고기김치찜',
 '육포',
 '크래커',
 '햄',
 '김치전',
 '백반',
 '비빔밥',
 '조개탕',
 '바지락칼국수',
 '딸기',
 '과일파르페',
 '튀김',
 '생크림케이크',
 '고기만두',
 '계란말이',
 '견과류',
 '바나나',
 '카스테라',
 '족발',
 '소불고기',
 '군만두',
 '중국식냉채',
 '삼겹살',
 '오징어땅콩',
 '바닐라아이스크림',
 '마라탕',
 '돼지갈비찜',
 '두부구이',
 '버섯전골',
 '두부',
 '순대',
 '치즈케이크',
 '해물라면',
 '코다리찜',
 '프로슈